services:
  payload:
    image: ghcr.io/gayabarumalamselatan/compro-bfs:latest
    container_name: compro-bfs
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ../cms-bfs/media/products:/app/public/api/product-media/file:ro
      - ../cms-bfs/media/products:/app/public/product-media:ro
      - ../cms-bfs/media/admin:/app/public/api/media/file:ro
      - ../cms-bfs/media/admin:/app/public/media:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
